<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Lazcat.Infrastructure" Version="1.0.9" />
        <PackageReference Include="SpanJson" Version="4.0.5" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Locations" />
        <Folder Include="Shared" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Airelax.Infrastructure\Airelax.Infrastructure.csproj" />
    </ItemGroup>

</Project>
