<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="12.0.1" />
        <PackageReference Include="Lazcat.Infrastructure" Version="1.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="SpanJson" Version="4.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Airelax.Domain\Airelax.Domain.csproj" />
        <ProjectReference Include="..\Airelax.Infrastructure\Airelax.Infrastructure.csproj" />
    </ItemGroup>
</Project>
